### PR TITLE
sched name must be url encoded; not CGI

### PR DESCRIPTION
**Pull request by nurse**

### CODE REVIEW

**Comment by nahi** [comment]
@nurse I agreed that it's a bug to be fixed, and sched name must be the one. But there are many other name we should handle like this fix ex. table name, database name and user name. Do you think we can do consistent bug fix for all of those?

IIRC I once tried this fix but then some tests failed...

**Comment by nurse** [comment]
>  table name, database name and user name

they can't include spaces.

**Comment by nahi** [comment]
> they can't include spaces.

I know, but that's API thing. We should keep using ```eu``` when we embed name in URL... if possible.

**Comment by nurse** [comment]
> I know, but that's API thing. We should keep using eu when we embed name in URL... if possible.

Of course it is possible, but it is really P2?

**Comment by mcaramello** [comment]
@nurse there are already 2 customers complaining about this problem and I suspect more will complain since the CLI is not usable in this 'td sched' context. So I guess it's a P2 if not P1.

**Comment by mcaramello** [comment]
Related or duplicate of #44

**Comment by nurse** [comment]
@mcaramello yeah, this issue affects customers, and I thought this fix should be conservative. But nahi says we should do comprehensive fix. I meant such large fix shouldn't be in the P2 scope.

Anyway I just notice a better way to fix, which simply not to encode spaces into '+' but %20 (and "+" into "%2b"). Even if it may affect some tests but compatibility for real API is expected to be kept. (of course, required checks will be larger than initial patch)

**Pull request closed without merging**
