### PR TITLE
Return job duration value by job:list

### LINKED ISSUE #30: add 'Job#duration' to job:list resulting value
API returns but td-client-ruby ignores it.

### PR DESCRIPTION
**Pull request by yoshihara**
fixes #30 .

### CODE REVIEW

**Comment by yoshihara** [comment]
If you want to look `job#duration` by `td job:list` command, more PR is needed for [td](https://github.com/treasure-data/td-client-ruby) to show this value. Could I make this PR too?

**Comment by nahi** [comment]
@yoshihara Ah, definitely. Would you please do that, with taking care of impact to td commands from Job model change?

**Comment by yoshihara** [comment]
@nahi Yes I'd love to :) I'll create PR for it, so wait a minute please.

**Comment by yoshihara** [comment]
@nahi I created PR (https://github.com/treasure-data/td/pull/61), so could you review this ? (Job model seems to be broken by me, but if this PR breaks it, please comment it :bow: )

**Comment by nahi** [comment]
:+1:

**Pull request merged**
