### PR TITLE
Change default endpoint

### LINKED ISSUE #28: Change DEFAULT_ENDPOINT to api.treasuredata.com
Because it's the default endpoint now. td-agent should follow.

### PR DESCRIPTION
**Pull request by uu59**
Fix #28 #29 #40

### CODE REVIEW

**Comment by nahi** [comment]
Thank you! I'm going to merge this in the next minor (not teeny) release.

**Comment by takkanm** [comment]
@nahi I fixed following items. https://github.com/treasure-data/td-client-ruby/commit/94cb22293524d21529746f704b485739ec762754

- import api endpoint is `api-import.treasuredata.com`
- default ssl

please, review it.

**Comment by nahi** [comment]
Thanks @uu59 and @takkanm for taking care of this, and sorry for confusing you long time.

Can we make "api.treasure-data.com" as a constant like 'OLD_~' to clarify the intension? Others looks good to me.

**Comment by takkanm** [comment]
I replaced to `OLD_ENDPOINT` from 'api.treasure-data.com`.

**Pull request merged**
